# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: hohuyhoang01011990@gmail.com
author_name: hoangho
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: myextension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension.
python_name: myextension
repository: https://github.com/huyhoang1990/hoangho-extension
test: true
viewer_name: ''

